fx_version 'adamant'

game 'gta5'

version '1.0'

data_file 'DLC_ITYP_REQUEST' 'stream/brum_creamice_blue.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_creamice_chocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_creamice_green.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_creamice_pink.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_creamice_vanilla.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jardrink_blue.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jardrink_bluedark.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jardrink_green.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jardrink_lime.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jardrink_orange.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jardrink_pink.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jardrink_red.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jardrink_yellow.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_summercocktail_blue.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_summercocktail_green.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_summercocktail_lime.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_summercocktail_orange.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_summercocktail_pink.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_summercocktail_purple.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_summercocktail_red.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_summercocktail_yellow.ytyp'